const STORAGE_KEY="job-application-tracker:v1",THEME_KEY="job-application-tracker:theme";
const $=id=>document.getElementById(id);
const form=$("jobForm"),editIdInput=$("editId"),companyInput=$("company"),positionInput=$("position"),statusInput=$("status"),dateInput=$("date"),linkInput=$("link"),notesInput=$("notes"),saveBtn=$("saveBtn"),cancelEditBtn=$("cancelEditBtn"),searchInput=$("searchInput"),statusFilter=$("statusFilter"),jobsList=$("jobsList"),emptyState=$("emptyState"),template=$("jobCardTemplate"),exportBtn=$("exportBtn"),importInput=$("importInput"),themeToggle=$("themeToggle"),totalCount=$("totalCount"),appliedCount=$("appliedCount"),interviewCount=$("interviewCount"),offerCount=$("offerCount");
let applications=loadApplications();
dateInput.value=new Date().toISOString().split("T")[0];applySavedTheme();render();
function loadApplications(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(data)?data:[]}catch{return[]}}
function saveApplications(){localStorage.setItem(STORAGE_KEY,JSON.stringify(applications))}
function createId(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function sanitizeUrl(value){if(!value)return"";try{const parsed=new URL(value);return["http:","https:"].includes(parsed.protocol)?parsed.href:""}catch{return""}}
form.addEventListener("submit",event=>{event.preventDefault();const application={id:editIdInput.value||createId(),company:companyInput.value.trim(),position:positionInput.value.trim(),status:statusInput.value,date:dateInput.value,link:sanitizeUrl(linkInput.value.trim()),notes:notesInput.value.trim()};if(!application.company||!application.position||!application.date)return;const existingIndex=applications.findIndex(item=>item.id===application.id);if(existingIndex>=0)applications[existingIndex]=application;else applications.unshift(application);saveApplications();resetForm();render()});
cancelEditBtn.addEventListener("click",resetForm);searchInput.addEventListener("input",render);statusFilter.addEventListener("change",render);
exportBtn.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(applications,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`job-applications-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url)});
importInput.addEventListener("change",async()=>{const file=importInput.files?.[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!Array.isArray(imported))throw new Error("Invalid backup");applications=imported.filter(item=>item&&typeof item==="object").map(item=>({id:String(item.id||createId()),company:String(item.company||"").slice(0,80),position:String(item.position||"").slice(0,100),status:["Applied","Interview","Offer","Rejected"].includes(item.status)?item.status:"Applied",date:String(item.date||"").slice(0,10),link:sanitizeUrl(String(item.link||"")),notes:String(item.notes||"").slice(0,500)})).filter(item=>item.company&&item.position&&item.date);saveApplications();render()}catch{alert("Could not import this file. Please choose a valid tracker backup.")}finally{importInput.value=""}});
themeToggle.addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem(THEME_KEY,document.body.classList.contains("dark")?"dark":"light");updateThemeButton()});
function applySavedTheme(){if(localStorage.getItem(THEME_KEY)==="dark")document.body.classList.add("dark");updateThemeButton()}
function updateThemeButton(){themeToggle.textContent=document.body.classList.contains("dark")?"☀ Light":"☾ Dark"}
function resetForm(){form.reset();editIdInput.value="";dateInput.value=new Date().toISOString().split("T")[0];statusInput.value="Applied";saveBtn.textContent="Add application";cancelEditBtn.classList.add("hidden")}
function editApplication(id){const item=applications.find(application=>application.id===id);if(!item)return;editIdInput.value=item.id;companyInput.value=item.company;positionInput.value=item.position;statusInput.value=item.status;dateInput.value=item.date;linkInput.value=item.link||"";notesInput.value=item.notes||"";saveBtn.textContent="Save changes";cancelEditBtn.classList.remove("hidden");form.scrollIntoView({behavior:"smooth",block:"start"});companyInput.focus()}
function deleteApplication(id){const item=applications.find(application=>application.id===id);if(!item||!confirm(`Delete your application for "${item.position}" at ${item.company}?`))return;applications=applications.filter(application=>application.id!==id);saveApplications();render()}
function render(){renderStats();const query=searchInput.value.trim().toLowerCase(),filter=statusFilter.value,filtered=applications.filter(item=>(item.company.toLowerCase().includes(query)||item.position.toLowerCase().includes(query))&&(filter==="All"||item.status===filter)).sort((a,b)=>b.date.localeCompare(a.date));jobsList.replaceChildren();emptyState.classList.toggle("hidden",filtered.length>0);filtered.forEach(item=>{const card=template.content.firstElementChild.cloneNode(true);card.querySelector(".job-position").textContent=item.position;card.querySelector(".job-company").textContent=item.company;const badge=card.querySelector(".status-badge");badge.textContent=item.status;badge.classList.add(`status-${item.status}`);const date=new Date(`${item.date}T00:00:00`);card.querySelector(".job-date").textContent=Number.isNaN(date.getTime())?item.date:`Applied ${date.toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})}`;const link=card.querySelector(".job-link");if(item.link)link.href=item.link;else link.remove();const notes=card.querySelector(".job-notes");if(item.notes)notes.textContent=item.notes;else notes.remove();card.querySelector(".edit-btn").addEventListener("click",()=>editApplication(item.id));card.querySelector(".delete-btn").addEventListener("click",()=>deleteApplication(item.id));jobsList.append(card)})}
function renderStats(){totalCount.textContent=applications.length;appliedCount.textContent=applications.filter(item=>item.status==="Applied").length;interviewCount.textContent=applications.filter(item=>item.status==="Interview").length;offerCount.textContent=applications.filter(item=>item.status==="Offer").length}